In [27]:
import snowflake.connector as sf

In [28]:
import pandas as pd

In [29]:
user=""
password=""
account="";
database=""
warehouse=""
schema=""
role=""

In [31]:
conn=sf.connect(user=user,password=password,account=account);

In [32]:
def run_query(connection,query):
    cursor=conn.cursor();
    cursor.execute(query);
    cursor.close();

In [33]:
statement_1='use warehouse '+warehouse;
statement2='alter warehouse '+warehouse+" resume";
statement3="use database "+database;
statement4="use role "+role;

In [34]:
run_query(conn,statement_1)
run_query(conn,statement2)
run_query(conn,statement3)
run_query(conn,statement4)

In [35]:
sql_st='select * from video limit 20';
df=pd.read_sql(sql_st,conn)

In [36]:
df.head(20)

    SEPAL_LENGTH  SEPAL_WIDTH  PETAL_LENGTH  PETAL_WIDTH        CLASSNAME
0            7.0          3.2           4.7          1.4  Iris-versicolor
1            6.4          3.2           4.5          1.5  Iris-versicolor
2            6.9          3.1           4.9          1.5  Iris-versicolor
3            5.5          2.3           4.0          1.3  Iris-versicolor
4            6.5          2.8           4.6          1.5  Iris-versicolor
5            5.7          2.8           4.5          1.3  Iris-versicolor
6            6.3          3.3           4.7          1.6  Iris-versicolor
7            4.9          2.4           3.3          1.0  Iris-versicolor
8            6.6          2.9           4.6          1.3  Iris-versicolor
9            5.2          2.7           3.9          1.4  Iris-versicolor
10           5.0          2.0           3.5          1.0  Iris-versicolor
11           5.9          3.0           4.2          1.5  Iris-versicolor
12           6.0          2.2           4.0          1.0  Iris-versicolor
13           6.1          2.9           4.7          1.4  Iris-versicolor
14           5.6          2.9           3.6          1.3  Iris-versicolor
15           6.7          3.1           4.4          1.4  Iris-versicolor
16           5.6          3.0           4.5          1.5  Iris-versicolor
17           5.8          2.7           4.1          1.0  Iris-versicolor
18           6.2          2.2           4.5          1.5  Iris-versicolor
19           5.6          2.5           3.9          1.1  Iris-versicolor